services:
  postgres:
    container_name: postgresDB_container
    image: postgres
    environment:
      POSTGRES_USER: sahansha
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "9090:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MOVE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5056:80"
    networks:
      - postgres
    restart: unless-stopped


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
